export * as gravityMsgProto from "./gravity/proto-types/msgs"
export * as gravityQueryProto from"./gravity/proto-types/query"
export * as groupMsgProto from "./group/proto-types/tx.pb"
export * as groupQueryProto from"./group/proto-types/query.pb"
export * as nftMsgProto from "./nft/proto-types/tx"
export * as nftQueryProto from"./nft/proto-types/query"
